### ISSUE TITLE
Using custom docker registries

### ISSUE THREAD

**Issue by mikeslinkman** [vbem/multi-runners#6]
Hi, 

Thanks for creating the package, after my last issue I was able to create the runners so thanks for the update. But now I'm facing another issue. Some of my docker images are in a private registry, so I ensured that my server can access the registry. I verified that by using the default GitHub runner which can successfully pull images from there.

But all the runners that I've added using this tool can't access this repository although they are added on the same server. Did I miss anything in the readme that I need to do to ensure these runners can also access the registry?

**Comment by mikeslinkman** [comment]
Closing this as not an issue, just noticed in the action runner documentation how to do it properly.

```
    container:
      image: REGISTRY_URL
      credentials:
        username: REGISTERY_USERNAME
        password: ${{ secrets.REGISTRY_PASSWORD }}
```
